services:
  db:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: spotify
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    restart: unless-stopped

  redis:
    container_name: cachedb
    image: redis:latest
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    restart: unless-stopped


