spring:
  application:
    name: music-service-api

  datasource:
    url: jdbc:mysql://localhost:3306/spotify
    username: username
    password: password

  data:
    redis:
      host: localhost
      port: 6379

  flyway:
    baseline-on-migrate: true
    clean-disabled: false
    user: username
    password: password
    url: jdbc:mysql://localhost:3306/spotify

  servlet:
    multipart:
      max-file-size: 10MB

application:
  security:
    jwt:
      secretKey: mysupersecretkeyihavetomakeitlongoriwillgetanexceptionfortooshortlmao
      jwtExpiration: 86400000

s3:
  bucket:
    name: music-platform
  access:
    key: user
  secret:
    key: password
  endpoint:
    url: http://localhost:9000
  region: us-east-1

logging:
  level:
    com.tranhuy105.musicserviceapi: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG